version: '3.3'
services:
  # message-broker:
  #   image: rabbitmq:3.8-management
  #   hostname: message-broker
  #   restart: always
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  mongo:
    image: mongo:4.4.5
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    networks: 
      - spots-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  spots-eureka:
    image: 'spots-eureka:0.0.1-SNAPSHOT'
    container_name: spots-eureka
    hostname: spots-eureka
    networks: 
      - spots-network
    ports:
        - "8761:8761"

  spots-gateway:
    image:  'spots-gateway:0.0.1-SNAPSHOT'
    container_name: spots-gateway
    ports:
        - "8080:8080"
    links:
        - "spots-eureka"
    networks: 
      - spots-network
    environment:
      eureka_client_serviceUrl_defaultZone: http://spots-eureka:8761/eureka

  spotservice:
    image: 'spotservice:0.0.1-SNAPSHOT'
    container_name: spotservice
    hostname: spotservice
    build:
      context: .
    networks: 
      - spots-network
    environment:
      eureka_client_serviceUrl_defaultZone: http://spots-eureka:8761/eureka

volumes:
  mongodb:

networks:
  spots-network:
    driver: bridge
