global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spots-gateway'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['spots-gateway:443']
