version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: Zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: Kafka
    ports:
    - "9092:9092"
    expose:
    - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: 'INSIDE://:9093,OUTSIDE://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://localhost:9093, OUTSIDE://localhost:9092'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'     
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INSIDE'
    depends_on:
    - zookeeper
